// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIBwyq5RmQlBL5VIXzo4U-zuiMQhmTqm8',
    appId: '1:691667417290:web:3b9a5d5a83efbbd4ba1c33',
    messagingSenderId: '691667417290',
    projectId: 'firedummy-ba0db',
    authDomain: 'firedummy-ba0db.firebaseapp.com',
    storageBucket: 'firedummy-ba0db.appspot.com',
    measurementId: 'G-2TT7WQM80C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7fvbIFLlyRwVi1AEeVhOGS01XAG3ZQs8',
    appId: '1:691667417290:android:8ac22ad4ecf8e656ba1c33',
    messagingSenderId: '691667417290',
    projectId: 'firedummy-ba0db',
    storageBucket: 'firedummy-ba0db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADz0zUC8Nq2xVpLuhUSS_PpqqOT-XHotY',
    appId: '1:691667417290:ios:6a5f57e91e5f5ec5ba1c33',
    messagingSenderId: '691667417290',
    projectId: 'firedummy-ba0db',
    storageBucket: 'firedummy-ba0db.appspot.com',
    iosBundleId: 'com.example.goldeneggProfit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADz0zUC8Nq2xVpLuhUSS_PpqqOT-XHotY',
    appId: '1:691667417290:ios:04b2a1500d5f827dba1c33',
    messagingSenderId: '691667417290',
    projectId: 'firedummy-ba0db',
    storageBucket: 'firedummy-ba0db.appspot.com',
    iosBundleId: 'com.example.goldeneggProfit.RunnerTests',
  );
}
